### ISSUE TITLE
repo-regexp работает не корректно

### ISSUE THREAD

**Issue by zmm** [OSLL/code-plagiarism#152]
codeplag check --extension py --github-user moevm --repo-regexp "devops-1h2023" --all-branches
 codeplag check --extension cpp --github-user moevm --repo-regexp 'devops-1'
codeplag check --extension cpp --github-user moevm --repo-regexp 'devops-'

команды выше находят в лучшем случае только https://github.com/moevm/devops-examples, хотя есть еще devops-1h2023 и devops-1h2022

**Comment by Artanias** [comment]
А если попробовать с '\bdevops-1'.

**Comment by zmm** [comment]
root@c4cfe720db05:/usr/src/codeplag# codeplag check --extension cpp --github-user moevm --repo-regexp '\bdevops-1'
[WARNING] 11:01 - Env file not found or not a file. Trying to get token from environment.
[INFO] 11:01 - Starting searching for plagiarism
[INFO] 11:01 - Found [] works
[]
[INFO] 11:01 - Ending searching for plagiarism.

токен передан - с ним все ок.

**Comment by Artanias** [comment]
Какие права у токена?

Т.к. это закрытые репозитории, то скорее всего может не хватать нужных прав, поэтому и находит только открытый `devops-examples`, у GitHub'а довольно таки странные настройки с токенами были, надо попробовать с разными, вроде только на read закрытых репозиториев не хватало.

Также а точно ли тот репозиторий есть, у меня его лично нет вообще.

**Comment by zmm** [comment]
Репозитории приватные. Я владелец организации и токен использую свой личный. По этому же токену я другими скриптами без проблем нахожу закрытые репо. Я вас добавил в репо devops-1h2023 и devops-1h2022 для тестов, попробуйте повторить мои запросы.

**Comment by Artanias** [comment]
Да, проблема не в токене, а в используемом API.
