### ISSUE TITLE
Поправить инструменты сборки докер-образа

### ISSUE THREAD

**Issue by zmm** [OSLL/code-plagiarism#155]
В текущем варианте, если мы уже собрали один раз докер образ и поменяли один файл у себя на машине, то при пересборке штатной командой через make изменения не попадут в образ

**Comment by Artanias** [comment]
1) Какая команда;
2) Какие файлы?
3) Прошлый образ удаляется при этом?

Есть некоторые моменты, которые сделаны, чтобы по каждому чиху не пересобирать образы и не тратить ресурсы.

**Comment by zmm** [comment]
1 Я использовал make docker-image для сборки.
2 Файлы *.py

**Comment by Artanias** [comment]
Если хотим пересобрать, то нужно будет явно удалить образ, сейчас проверяется, что образ уже есть, тогда и не пересобираем образ - https://github.com/OSLL/code-plagiarism/blob/9d0a4dd8f378088e0aa6eb421c48c4ae68eb8207/Makefile#L176.

Сейчас если хотим пересобрать, без пересборки некоторых промежуточных уровней можно выполнить:
```
$ make clean-all
$ docker rmi codeplag-ubuntu20.04:<current_version_in_makefile>
$ make docker-image
```

В таком случае удалятся некоторые верхние слои, а нижние базовые слои останутся в рамках образа c**odeplag-base-ubuntu20.04** и сборки не должна занять много времени, а новый код должен уже быть в образе.

**Comment by Artanias** [comment]
`make docker-image REBUILD=1`
