### ISSUE TITLE
Вынести отладочную информацию и содержательный результат (В логах работы программЫ) в разные потоки (stdout stderr)

### ISSUE THREAD

**Issue by zmm** [OSLL/code-plagiarism#156]
Сейчас печатается все вместе, студентам и преподавателям будет трудно в логах искать конкретику.
Предлагаю отделить непосредственно фидбек по плагиату в stdout, все остальное - stderr.

**Comment by Artanias** [comment]
Имеется в виду то что пишется на консоль?

Ок, благо logging это позволяет делать без труда.

Будет так:
Всё, что < warning -> stdout
Всё, что >= warning -> stderr
Как обычно это принято.

**Comment by zmm** [comment]
Да, я имел в виду именно то, что пишется в консоль, спасибо!
Также, я бы предложил выводить в отладочные логи некую промежуточную информацию по общему списку проверяемых файлов / директорий / репо (сколько всего кандидатов на проверку , из чего состоит список) - так будет проще отладить использование приложения и понять, что пользователи делают не так.

**Comment by Artanias** [comment]
> Также, я бы предложил выводить в отладочные логи некую промежуточную информацию по общему списку проверяемых файлов / директорий / репо (сколько всего кандидатов на проверку , из чего состоит список) - так будет проще отладить использование приложения и понять, что пользователи делают не так.

#162
