### ISSUE TITLE
Пример списанного кода, проходящий проверку на плагиат

### ISSUE THREAD

**Issue by mirrin00** [OSLL/code-plagiarism#163]
[Исходный код](https://github.com/test-github-action/pr-2022-2382/blob/weak_plagiarism/weak_plagiarism/main_origin.c), [списанный код](https://github.com/test-github-action/pr-2022-2382/blob/weak_plagiarism/weak_plagiarism/main_plagiarism.c) с некоторыми изменениями: использование переменных вместо констант, более простых операторов языка Си, фиктивных переменных.  Результат поиска плагиата:
* По быстрым метриками -- 64.80%
* Полное сравнение -- 64.98%

Кажется, что это низкий процент похожести, а должен быть больше.

Использовалась версия из докера `artanias/codeplag-ubuntu20.04:0.3.0`

**Comment by Artanias** [comment]
Очень спорно, т.к. всё-таки достаточно в работах содержится хоть и маленьких, но изменений, чтобы казаться разными, если по быстрым метрикам такой процент, то всё-таки тут уже стоит просто изначально обговаривать какой порог нужно проходить и какой считать терпимым, 60%+ для таких работ кажется нормальным значением (т.к. небольшой объём, а также есть разница в нескольких местах).
Также т.к. работы достаточно небольшие, то и вероятность того, что они будут похожи между собой выше.
